name: Tests

on:
    pull_request:
        branches: ['**']
        paths-ignore:
            - '**/*.md'
            - 'static/**/*'

env:
    VITE_APPWRITE_ENDPOINT: http://appwrite.test/v1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Audit dependencies
              run: npm audit --audit-level critical
            - name: Install dependencies
              run: npm ci
            - name: Svelte Diagnostics
              run: npm run check
            - name: Linter
              run: npm run lint
            - name: Unit Tests
              run: npm run test
            - name: Build Console
              run: npm run build
